# Generated by Django 5.0.6 on 2024-05-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0002_remove_requirement_file_requirementfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementfile',
            name='name',
            field=models.CharField(default=0, max_length=200, verbose_name='Наименование файла'),
            preserve_default=False,
        ),
    ]
