# Generated by Django 5.0.6 on 2024-06-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_autonomicgs_price2022_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadgs',
            name='price2026',
            field=models.IntegerField(default=0, verbose_name='Стоимость за ед.изм., руб./м(2026г.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roadgs',
            name='price2027',
            field=models.IntegerField(default=0, verbose_name='Стоимость за ед.изм., руб./м(2027г.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roadgs',
            name='price_all2026',
            field=models.IntegerField(default=0, verbose_name='Стоимость всего, руб.(2026г.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roadgs',
            name='price_all2027',
            field=models.IntegerField(default=0, verbose_name='Стоимость всего, руб.(2027г.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roadgs',
            name='quantity_m2026',
            field=models.IntegerField(default=0, verbose_name='Кол-во всего, метры (2026г.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roadgs',
            name='quantity_m2027',
            field=models.IntegerField(default=0, verbose_name='Кол-во всего, метры (2027г.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roadgs',
            name='quantity_well2026',
            field=models.IntegerField(default=0, verbose_name='Кол-во скважин (2026г.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roadgs',
            name='quantity_well2027',
            field=models.IntegerField(default=0, verbose_name='Кол-во скважин (2027г.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roadnns',
            name='price2026',
            field=models.IntegerField(default=0, verbose_name='Стоимость за ед.изм., руб./м(2026г.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roadnns',
            name='price2027',
            field=models.IntegerField(default=0, verbose_name='Стоимость за ед.изм., руб./м(2027г.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roadnns',
            name='price_all2026',
            field=models.IntegerField(default=0, verbose_name='Стоимость всего, руб.(2026г.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roadnns',
            name='price_all2027',
            field=models.IntegerField(default=0, verbose_name='Стоимость всего, руб.(2027г.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roadnns',
            name='quantity_m2026',
            field=models.IntegerField(default=0, verbose_name='Кол-во всего, метры (2026г.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roadnns',
            name='quantity_m2027',
            field=models.IntegerField(default=0, verbose_name='Кол-во всего, метры (2027г.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roadnns',
            name='quantity_well2026',
            field=models.IntegerField(default=0, verbose_name='Кол-во скважин (2026г.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roadnns',
            name='quantity_well2027',
            field=models.IntegerField(default=0, verbose_name='Кол-во скважин (2027г.)'),
            preserve_default=False,
        ),
    ]
